name: AutoBuild .NET

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - name: Run Python script
        run: python stringToDat.py

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Build
        run: dotnet build Peasmod4/Peasmod4.csproj --configuration Dev

      - name: Upload Peasmod4
        uses: actions/upload-artifact@v4
        with:
          name: Peasmod4.dll
          path: Peasmod4/bin/Dev/net6.0/Peasmod4.dll    